spring.application.name=passnav-api

# Choose a port for the backend, 8080 is the default port number
# server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=
spring.datasource.password=

# Replace localhost with the database host, 3306 with port number, and passnav with database name
spring.datasource.url=jdbc:mysql://localhost:3306/passnav

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Uncomment to see the SQL queries executed by the framework
# spring.jpa.show-sql=true

# Uncomment to see the log level for the SQL logger
# logging.level.org.hibernate.SQL=DEBUG

springdoc.swagger-ui.path=api-docs
